# Generated by Django 2.1.7 on 2019-06-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('peso', models.IntegerField(verbose_name='Peso')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(verbose_name='Peso')),
                ('inicio', models.DateField(verbose_name='Data de Início')),
                ('fim', models.DateField(verbose_name='Data de Fim')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=10000, verbose_name='Texto')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos', verbose_name='Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=500, verbose_name='Comando')),
                ('peso', models.IntegerField(verbose_name='Peso')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=14, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('professor', models.BooleanField(verbose_name='Professor')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='usuarios',
            field=models.ManyToManyField(to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(limit_choices_to={'professor': False}, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turmas',
            field=models.ManyToManyField(to='core.Turma'),
        ),
    ]
