# Generated by Django 2.2.2 on 2019-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='fim',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='inicio',
            field=models.DateTimeField(verbose_name='Início'),
        ),
    ]
